"""Loading and matching for the mined attribute vocabularies.

Each gazetteer is two files: `<kind>.txt`, regenerated by 05_mine_gazetteers.py
from the corpus, and `<kind>_manual.txt`, hand-maintained for terms the corpus
cannot supply. Both are merged at load time; the generated file is never edited
by hand because the next mining run would discard the edit.
"""
from __future__ import annotations

import re
from functools import lru_cache

from . import config

GAZETTEER_DIR = config.WORK_DIR / "data" / "gazetteers"

KINDS = ("material", "property", "environment")


def _read_terms(path) -> set[str]:
    if not path.exists():
        return set()
    terms = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            terms.add(line.lower())
    return terms


@lru_cache(maxsize=None)
def load_gazetteer(kind: str) -> frozenset[str]:
    """Mined terms plus hand-added ones, for one attribute kind."""
    mined = _read_terms(GAZETTEER_DIR / f"{kind}.txt")
    manual = _read_terms(GAZETTEER_DIR / f"{kind}_manual.txt")
    return frozenset(mined | manual)


@lru_cache(maxsize=None)
def _matcher(kind: str) -> re.Pattern | None:
    terms = load_gazetteer(kind)
    if not terms:
        return None
    # Longest first, so "stainless steel" wins over "steel" at the same position.
    ordered = sorted(terms, key=len, reverse=True)
    return re.compile(r"\b(?:" + "|".join(re.escape(t) for t in ordered) + r")\b", re.IGNORECASE)


def find_terms(text: str, kind: str) -> list[str]:
    """Gazetteer terms present in the text, longest match first, deduplicated.

    A term contained inside a longer match is dropped, so "stainless steel"
    never also reports a bare "steel".
    """
    matcher = _matcher(kind)
    if matcher is None or not text:
        return []
    spans: list[tuple[int, int, str]] = []
    for match in matcher.finditer(text):
        start, end = match.span()
        if any(start >= s and end <= e for s, e, _ in spans):
            continue
        spans.append((start, end, match.group(0).lower()))
    out: list[str] = []
    for _, _, term in sorted(spans):
        if term not in out:
            out.append(term)
    return out


def reset_cache() -> None:
    """Drop cached gazetteers, for tests that write the files."""
    load_gazetteer.cache_clear()
    _matcher.cache_clear()
