import type { LanguageCode } from "./index";

type LocaleWords = {
  dashboard: string; analyzeTender: string; settings: string; heading: string; subheading: string; placeholder: string;
  analyze: string; example: string; led: string; pump: string; upload: string; drop: string; pdf: string;
  appearance: string; language: string; preferences: string; recommendations: string; system: string; light: string; dark: string;
  status: string; online: string; offline: string; about: string; aboutBody: string; describe: string; uploadTender: string;
  history?: string; recentAnalyses?: string; yourHistory?: string; clearHistory?: string; noAnalyses?: string; analyzeTenderAction?: string; justNow?: string; minutesAgo?: string; hoursAgo?: string; daysAgo?: string;
  stepOne?: string; stepOneBody?: string; stepTwo?: string; stepTwoBody?: string; stepThree?: string; stepThreeBody?: string;
  characters: string; clear: string; remove: string; extracting: string; error: string; retry: string; newAnalysis: string;
};

const base = (w: LocaleWords) => ({
  nav: { dashboard: w.dashboard, analyze: w.analyzeTender, history: w.history ?? "History", settings: w.settings, about: w.about },
  dashboard: {
    heading: w.heading, subheading: w.subheading, placeholder: w.placeholder, analyze: w.analyze, tryExample: w.example,
    examples: { led: w.led, pump: w.pump }, uploadTitle: w.drop, uploadSubtitle: w.pdf,
    backendOffline: w.offline, checking: `${w.status}…`,
    steps: { oneTitle: w.stepOne ?? w.describe, oneBody: w.stepOneBody ?? w.subheading, twoTitle: w.stepTwo ?? w.example, twoBody: w.stepTwoBody ?? w.aboutBody, threeTitle: w.stepThree ?? w.analyze, threeBody: w.stepThreeBody ?? w.aboutBody },
  },
  analyze: {
    modeText: w.describe, modeUpload: w.uploadTender, charCount: `{{count}} ${w.characters}`, clear: w.clear,
    analyzeButton: w.analyze, language: w.language,
    examples: { led: w.led, pumps: w.pump, cables: w.led }, removeFile: w.remove, extracting: w.extracting,
    steps: { uploading: w.uploadTender, extracting: w.extracting, understanding: w.analyze, searching: w.analyze, building: w.analyze, evidence: w.analyze, done: w.analyze },
  },
  settings: {
    title: w.settings, appearance: w.appearance, light: w.light, dark: w.dark, system: w.system, language: w.language,
    preferences: w.preferences, topK: w.recommendations, about: w.about, aboutBody: w.aboutBody,
    systemStatus: w.status, backendOnline: w.online, backendOffline: w.offline, standardsLoaded: `{{count}} ${w.recommendations}`,
  },
  results: { newAnalysis: w.newAnalysis },
  history: { recentAnalyses: w.recentAnalyses ?? "Recent analyses", yourHistory: w.yourHistory ?? "Your analysis history", clear: w.clearHistory ?? w.clear, emptyTitle: w.noAnalyses ?? "No analyses yet", emptyBody: w.noAnalyses ?? "No analyses yet — results from your searches will show up here.", analyze: w.analyzeTenderAction ?? w.analyzeTender, justNow: w.justNow ?? "just now", minutesAgo: w.minutesAgo ?? "{{count}} minutes ago", hoursAgo: w.hoursAgo ?? "{{count}} hours ago", daysAgo: w.daysAgo ?? "{{count}} days ago" },
  about: { howItWorks: w.stepOne ? "कार्यप्रणाली" : w.about, stepOneTitle: w.stepOne ?? w.describe, stepOne: w.stepOneBody ?? w.subheading, stepTwoTitle: w.stepTwo ?? w.example, stepTwo: w.stepTwoBody ?? w.aboutBody, stepThreeTitle: w.stepThree ?? w.analyze, stepThree: w.stepThreeBody ?? w.aboutBody, standardsIndexed: w.recommendations, targetLanguages: w.language, projectLine: w.about },
  errors: { generic: w.error, fileTooLarge: w.error, unsupportedFile: w.error, emptyQuery: w.error, retry: w.retry },
});

const words: Record<string, LocaleWords> = {
  as: { dashboard: "ডেশ্বব'ৰ্ড", analyzeTender: "নিবিদা বিশ্লেষণ", settings: "ছেটিংছ", heading: "আপুনি আজি কি ক্ৰয় কৰিছে?", subheading: "এটা সামগ্ৰী বা প্ৰয়োজনীয়তা বৰ্ণনা কৰক, অথবা নিবিদা আপলোড কৰি প্ৰযোজ্য ভাৰতীয় মান বিচাৰক।", placeholder: "যেনে: বাহিৰৰ পৌৰসভাৰ পথৰ বাবে 90W LED ষ্ট্ৰীট লাইট", analyze: "বিশ্লেষণ", example: "এটা উদাহৰণ চেষ্টা কৰক", led: "90W LED ষ্ট্ৰীট লাইট", pump: "কেন্দ্ৰাতিগ পানী পাম্প", upload: "নিবিদা আপলোড কৰক", drop: "ইয়াত নিবিদা দিয়ক", pdf: "PDF বা TXT, 25MB লৈকে", appearance: "ৰূপ", language: "ভাষা", preferences: "বিশ্লেষণৰ পছন্দ", recommendations: "পৰামৰ্শ", system: "চিস্টেম", light: "পোহৰ", dark: "আন্ধাৰ", status: "চিস্টেমৰ অৱস্থা", online: "বেকএণ্ড অনলাইন", offline: "বেকএণ্ড অফলাইন", about: "IS-Advisor ৰ বিষয়ে", aboutBody: "IS-Advisor-এ প্ৰযোজ্য ভাৰতীয় মানৰ পৰামৰ্শ দিয়ে।", describe: "ক্ৰয়ৰ প্ৰয়োজনীয়তা বৰ্ণনা কৰক", uploadTender: "নিবিদা আপলোড কৰক", characters: "আখৰ", clear: "পৰিষ্কাৰ", remove: "আঁতৰাওক", extracting: "নথিৰ পৰা পাঠ উলিওৱা হৈছে…", error: "কিবা এটা ভুল হৈছে। পুনৰ চেষ্টা কৰক।", retry: "পুনৰ চেষ্টা", newAnalysis: "নতুন বিশ্লেষণ" },
  bn: { dashboard: "ড্যাশবোর্ড", analyzeTender: "টেন্ডার বিশ্লেষণ", settings: "সেটিংস", heading: "আজ আপনি কী কিনছেন?", subheading: "একটি পণ্য বা প্রয়োজনীয়তা লিখুন, অথবা প্রযোজ্য ভারতীয় মান খুঁজতে টেন্ডার আপলোড করুন।", placeholder: "যেমন: পৌরসভার বাইরের রাস্তার জন্য 90W LED স্ট্রিট লাইট", analyze: "বিশ্লেষণ", example: "একটি উদাহরণ চেষ্টা করুন", led: "90W LED স্ট্রিট লাইট", pump: "কেন্দ্রাতিগ জল পাম্প", upload: "টেন্ডার আপলোড করুন", drop: "এখানে টেন্ডার দিন", pdf: "PDF বা TXT, সর্বোচ্চ 25MB", appearance: "চেহারা", language: "ভাষা", preferences: "বিশ্লেষণের পছন্দ", recommendations: "সুপারিশ", system: "সিস্টেম", light: "আলো", dark: "অন্ধকার", status: "সিস্টেমের অবস্থা", online: "ব্যাকএন্ড অনলাইন", offline: "ব্যাকএন্ড অফলাইন", about: "IS-Advisor সম্পর্কে", aboutBody: "IS-Advisor ক্রয়ের জন্য প্রযোজ্য ভারতীয় মানের সুপারিশ করে।", describe: "ক্রয়ের প্রয়োজনীয়তা বর্ণনা করুন", uploadTender: "টেন্ডার আপলোড করুন", characters: "অক্ষর", clear: "পরিষ্কার", remove: "সরান", extracting: "নথি থেকে পাঠ বের করা হচ্ছে…", error: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।", retry: "আবার চেষ্টা", newAnalysis: "নতুন বিশ্লেষণ", history: "ইতিহাস", recentAnalyses: "সাম্প্রতিক বিশ্লেষণ", yourHistory: "আপনার বিশ্লেষণের ইতিহাস", clearHistory: "ইতিহাস মুছুন", noAnalyses: "এখনও কোনো বিশ্লেষণ নেই", analyzeTenderAction: "টেন্ডার বিশ্লেষণ করুন", justNow: "এইমাত্র", minutesAgo: "{{count}} মিনিট আগে", hoursAgo: "{{count}} ঘণ্টা আগে", daysAgo: "{{count}} দিন আগে" },
  gu: { dashboard: "ડેશબોર્ડ", analyzeTender: "ટેન્ડર વિશ્લેષણ", settings: "સેટિંગ્સ", heading: "આજે તમે શું ખરીદી રહ્યા છો?", subheading: "ઉત્પાદન અથવા જરૂરિયાત લખો, અથવા લાગુ ભારતીય ધોરણો શોધવા ટેન્ડર અપલોડ કરો.", placeholder: "દા.ત. બહારના નગરપાલિકા રસ્તાઓ માટે 90W LED સ્ટ્રીટ લાઇટ", analyze: "વિશ્લેષણ", example: "ઉદાહરણ અજમાવો", led: "90W LED સ્ટ્રીટ લાઇટ", pump: "કેન્દ્રત્યાગી પાણી પંપ", upload: "ટેન્ડર અપલોડ કરો", drop: "અહીં ટેન્ડર મૂકો", pdf: "PDF અથવા TXT, 25MB સુધી", appearance: "દેખાવ", language: "ભાષા", preferences: "વિશ્લેષણ પસંદગીઓ", recommendations: "ભલામણો", system: "સિસ્ટમ", light: "પ્રકાશ", dark: "અંધારું", status: "સિસ્ટમ સ્થિતિ", online: "બેકએન્ડ ઑનલાઇન", offline: "બેકએન્ડ ઑફલાઇન", about: "IS-Advisor વિશે", aboutBody: "IS-Advisor ખરીદી માટે લાગુ ભારતીય ધોરણોની ભલામણ કરે છે.", describe: "ખરીદીની જરૂરિયાત વર્ણવો", uploadTender: "ટેન્ડર અપલોડ કરો", characters: "અક્ષરો", clear: "સાફ કરો", remove: "દૂર કરો", extracting: "દસ્તાવેજમાંથી લખાણ કાઢી રહ્યા છીએ…", error: "કંઈક ખોટું થયું. ફરી પ્રયાસ કરો.", retry: "ફરી પ્રયાસ", newAnalysis: "નવું વિશ્લેષણ" },
  kn: { dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", analyzeTender: "ಟೆಂಡರ್ ವಿಶ್ಲೇಷಣೆ", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", heading: "ಇಂದು ನೀವು ಏನು ಖರೀದಿಸುತ್ತಿದ್ದೀರಿ?", subheading: "ಉತ್ಪನ್ನ ಅಥವಾ ಅವಶ್ಯಕತೆಯನ್ನು ವಿವರಿಸಿ, ಅಥವಾ ಅನ್ವಯವಾಗುವ ಭಾರತೀಯ ಮಾನದಂಡಗಳನ್ನು ಹುಡುಕಲು ಟೆಂಡರ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.", placeholder: "ಉದಾ: ಹೊರಾಂಗಣ ಪುರಸಭೆ ರಸ್ತೆಗಳಿಗಾಗಿ 90W LED ಬೀದಿ ದೀಪಗಳು", analyze: "ವಿಶ್ಲೇಷಿಸಿ", example: "ಉದಾಹರಣೆ ಪ್ರಯತ್ನಿಸಿ", led: "90W LED ಬೀದಿ ದೀಪಗಳು", pump: "ಕೇಂದ್ರಾಪಗಾಮಿ ನೀರಿನ ಪಂಪ್‌ಗಳು", upload: "ಟೆಂಡರ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ", drop: "ಟೆಂಡರ್ ಇಲ್ಲಿ ಹಾಕಿ", pdf: "PDF ಅಥವಾ TXT, 25MB ವರೆಗೆ", appearance: "ಗೋಚರತೆ", language: "ಭಾಷೆ", preferences: "ವಿಶ್ಲೇಷಣೆ ಆದ್ಯತೆಗಳು", recommendations: "ಶಿಫಾರಸುಗಳು", system: "ಸಿಸ್ಟಮ್", light: "ಬೆಳಕು", dark: "ಕತ್ತಲೆ", status: "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ", online: "ಬ್ಯಾಕ���ಂಡ್ ಆನ್‌ಲೈನ್", offline: "ಬ್ಯಾಕೆಂಡ್ ಆಫ್‌ಲೈನ್", about: "IS-Advisor ಕುರಿತು", aboutBody: "IS-Advisor ಖರೀದಿಗಾಗಿ ಅನ್ವಯವಾಗುವ ಭಾರತೀಯ ಮಾನದಂಡಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ.", describe: "ಖರೀದಿ ಅವಶ್ಯಕತೆಯನ್ನು ವಿವರಿಸಿ", uploadTender: "ಟೆಂಡರ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ", characters: "ಅಕ್ಷರಗಳು", clear: "ತೆರವುಗೊಳಿಸಿ", remove: "ತೆಗೆದುಹಾಕಿ", extracting: "ದಾಖಲೆಯಿಂದ ಪಠ್ಯ ಹೊರತೆಗೆಯಲಾಗುತ್ತಿದೆ…", error: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", newAnalysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ" },
  ml: { dashboard: "ഡാഷ്ബോർഡ്", analyzeTender: "ടെൻഡർ വിശകലനം", settings: "ക്രമീകരണങ്ങൾ", heading: "ഇന്ന് നിങ്ങൾ എന്താണ് വാങ്ങുന്നത്?", subheading: "ഒരു ഉൽപ്പന്നമോ ആവശ്യകതയോ വിവരിക്കുക, അല്ലെങ്കിൽ ബാധകമായ ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ കണ്ടെത്താൻ ടെൻഡർ അപ്‌ലോഡ് ചെയ്യുക.", placeholder: "ഉദാ: പുറത്തെ മുനിസിപ്പൽ റോഡുകൾക്കുള്ള 90W LED തെരുവ് വിളക്കുകൾ", analyze: "വിശകലനം", example: "ഒരു ഉദാഹരണം ശ്രമിക്കുക", led: "90W LED തെരുവ് വിളക്കുകൾ", pump: "കേന്ദ്രാഭിമുഖ ജല പമ്പുകൾ", upload: "ടെൻഡർ അപ്‌ലോഡ് ചെയ്യുക", drop: "ടെൻഡർ ഇവിടെ ഇടുക", pdf: "PDF അല്ലെങ്കിൽ TXT, 25MB വരെ", appearance: "രൂപം", language: "ഭാഷ", preferences: "വിശകലന മുൻഗണനകൾ", recommendations: "ശുപാർശകൾ", system: "സിസ്റ്റം", light: "വെളിച്ചം", dark: "ഇരുട്ട്", status: "സിസ്റ്റം നില", online: "ബാക്കെൻഡ് ഓൺലൈൻ", offline: "ബാക്കെൻഡ് ഓഫ്‌ലൈൻ", about: "IS-Advisor-നെ കുറിച്ച്", aboutBody: "വാങ്ങലിനായി ബാധകമായ ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ IS-Advisor ശുപാർശ ചെയ്യുന്നു.", describe: "വാങ്ങൽ ആവശ്യകത വിവരിക്കുക", uploadTender: "ടെൻഡർ അപ്‌ലോഡ് ചെയ്യുക", characters: "അക്ഷരങ്ങൾ", clear: "മായ്��്കുക", remove: "നീക്കം ചെയ്യുക", extracting: "രേഖയിൽ നിന്ന് ���ാചകം എടുക്കുന്നു…", error: "എന്തോ തെറ്റായി. വീണ്ടും ശ്രമിക്കുക.", retry: "വീണ്ടും ശ്രമിക്കുക", newAnalysis: "പുതിയ വിശകലനം" },
  mr: { dashboard: "डॅशबोर्ड", analyzeTender: "निविदेचे विश्लेषण", settings: "सेटिंग्ज", heading: "आज तुम्ही काय खरेदी करत आहात?", subheading: "उत्पादन किंवा गरज सांगा, किंवा लागू भारतीय मानके शोधण्यासाठी निविदा अपलोड करा.", placeholder: "उदा. बाहेरील नगरपालिका रस्त्यांसाठी 90W LED स्ट्रीट लाइट", analyze: "विश्लेषण", example: "उदाहरण वापरून पहा", led: "90W LED स्ट्रीट लाइट", pump: "केंद्रापसारी जलपंप", upload: "निविदा अपलोड करा", drop: "येथे निविदा टाका", pdf: "PDF किंवा TXT, 25MB पर्यंत", appearance: "स्वरूप", language: "भाषा", preferences: "विश्लेषण प्राधान्ये", recommendations: "शिफारसी", system: "प्रणाली", light: "उजळ", dark: "गडद", status: "प्रणाली स्थिती", online: "बॅकएंड ऑनलाइन", offline: "बॅकएंड ऑफलाइन", about: "IS-Advisor विषयी", aboutBody: "IS-Advisor खरेदीसाठी लागू भारतीय मानकांची शिफारस करते.", describe: "खरेदीची गरज सांगा", uploadTender: "निविदा अपलोड करा", characters: "अक्षरे", clear: "पुसा", remove: "काढा", extracting: "दस्तऐवजातील मजकूर काढत आहे…", error: "काहीतरी चूक झाली. पुन्हा प्रयत्न करा.", retry: "पुन्हा प्रयत्न", newAnalysis: "नवीन विश्लेषण" },
  pa: { dashboard: "ਡੈਸ਼ਬੋਰਡ", analyzeTender: "ਟੈਂਡਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ", settings: "ਸੈਟਿੰਗਾਂ", heading: "ਤੁਸੀਂ ਅੱਜ ਕੀ ਖਰੀਦ ਰਹੇ ਹੋ?", subheading: "ਉਤਪਾਦ ਜਾਂ ਲੋੜ ਦੱਸੋ, ਜਾਂ ਲਾਗੂ ਭਾਰਤੀ ਮਿਆਰ ਲੱਭਣ ਲਈ ਟੈਂਡਰ ਅੱਪਲੋਡ ਕਰੋ।", placeholder: "ਉਦਾਹਰਨ: ਬਾਹਰੀ ਨਗਰਪਾਲਿਕਾ ਸੜਕਾਂ ਲਈ 90W LED ਸਟ੍ਰੀਟ ਲਾਈਟਾਂ", analyze: "ਵਿਸ਼ਲੇਸ਼ਣ", example: "ਇੱਕ ਉਦਾਹਰਨ ਅਜ਼ਮਾਓ", led: "90W LED ਸਟ੍ਰੀਟ ਲਾਈਟਾਂ", pump: "ਕੇਂਦਰਫਿਊਗਲ ਪਾਣੀ ਪੰਪ", upload: "ਟੈਂਡਰ ਅੱਪਲੋਡ ਕਰੋ", drop: "ਟੈਂਡਰ ਇੱਥੇ ਪਾਓ", pdf: "PDF ਜਾਂ TXT, 25MB ਤੱਕ", appearance: "ਦਿੱਖ", language: "ਭਾਸ਼ਾ", preferences: "ਵਿਸ਼ਲੇਸ਼ਣ ਤਰਜੀਹਾਂ", recommendations: "ਸਿਫ਼ਾਰਸ਼ਾਂ", system: "ਸਿ��ਟਮ", light: "ਰੌਸ਼ਨੀ", dark: "ਹਨੇਰਾ", status: "ਸਿਸਟਮ ਸਥਿਤੀ", online: "ਬੈਕਐਂਡ ਔਨਲਾਈਨ", offline: "ਬੈਕਐਂਡ ਔਫਲਾਈਨ", about: "IS-Advisor ਬਾਰੇ", aboutBody: "IS-Advisor ਖਰੀਦ ਲਈ ਲਾਗੂ ਭਾਰਤੀ ਮਿਆਰਾਂ ਦੀ ਸਿਫ਼ਾਰਸ਼ ਕਰਦਾ ਹੈ।", describe: "ਖਰੀਦ ਦੀ ਲੋੜ ਦੱਸੋ", uploadTender: "ਟੈਂਡਰ ਅੱਪਲੋਡ ਕਰੋ", characters: "ਅੱਖਰ", clear: "ਸਾਫ਼ ਕਰੋ", remove: "ਹਟਾਓ", extracting: "ਦਸਤਾਵੇਜ਼ ਤੋਂ ਪਾਠ ਕੱਢਿਆ ਜਾ ਰਿਹਾ ਹੈ…", error: "ਕੁਝ ਗਲਤ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", retry: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼", newAnalysis: "ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ" },
  ta: { dashboard: "டாஷ்போர்டு", analyzeTender: "டெண்டர் பகுப்பாய்வு", settings: "அமைப்புகள்", heading: "இன்று நீங்கள் எதை வாங்குகிறீர்கள்?", subheading: "ஒரு தயாரிப்பு அல்லது தேவையை விவரிக்கவும், அல்லது பொருந்தும் இந்திய தரநிலைகளைக் கண்டறிய டெண்டரைப் பதிவேற்றவும்.", placeholder: "எ.கா. வெளிப்புற நகராட்சி சாலைகளுக்கான 90W LED தெருவிளக்குகள்", analyze: "பகுப்பாய்வு", example: "ஓர் உதாரணத்தை முயற்சிக்கவும்", led: "90W LED தெருவிளக்குகள்", pump: "மையவிலக்கு நீர் பம்புகள்", upload: "டெண்டரைப் பதிவேற்றவும்", drop: "டெண்டரை இங்கே இடுங்கள்", pdf: "PDF அல்லது TXT, 25MB வரை", appearance: "தோற்றம்", language: "மொழி", preferences: "பகுப்பாய்வு விருப்பங்கள்", recommendations: "பரிந்துரைகள்", system: "கணினி", light: "வெளிச்சம்", dark: "இருள்", status: "கணினி நிலை", online: "பின்தளம் ஆன்லைன்", offline: "பின்தளம் ஆஃப்லைன்", about: "IS-Advisor பற்றி", aboutBody: "கொள்முதலுக்குப் பொருந்தும் இந்திய தரநிலைகளை IS-Advisor பரிந்துரைக்கிறது.", describe: "கொள்முதல் தேவையை விவரிக்கவும்", uploadTender: "டெண்டரைப் பதிவேற்றவும்", characters: "எழுத்துகள்", clear: "அழி", remove: "அகற்று", extracting: "ஆவணத்திலிருந்து உரை எடுக்கப்படுகிறது…", error: "ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.", retry: "மீண்டும் முயற்சி", newAnalysis: "புதிய பகுப்பாய்வு" },
  te: { dashboard: "డ్యాష్‌బోర్డ్", analyzeTender: "టెండర్ విశ్లేషణ", settings: "సెట్టింగ్‌లు", heading: "ఈరోజు మీరు ఏమి కొనుగోలు చేస్తున్నారు?", subheading: "ఉత్పత్తి లేదా అవసరాన్ని వివరించండి, లేదా వర్తించే భారతీయ ప్రమాణాలను కనుగొనడానికి టెండర్‌ను అప్‌లోడ్ చేయండి.", placeholder: "ఉదా: బయట మున్సిపల్ రోడ్ల కోసం 90W LED వీధి దీపాలు", analyze: "విశ్లేషించు", example: "ఉదాహరణ ప్రయత్నించండి", led: "90W LED వీధి దీపాలు", pump: "కేంద్రాపసారక నీటి పంపులు", upload: "టెండర్‌ను అప్‌లోడ్ చేయండి", drop: "టెండర్‌ను ఇక్కడ వేయండి", pdf: "PDF లేదా TXT, 25MB వరకు", appearance: "రూపురేఖలు", language: "భాష", preferences: "విశ్లేషణ ప్రాధాన్యతలు", recommendations: "సిఫార్సులు", system: "సిస్టమ్", light: "వెలుగు", dark: "చీకటి", status: "సిస్టమ్ స్థితి", online: "బ్యాకెండ్ ఆన్‌లైన్", offline: "బ్యాకెండ్ ఆఫ్‌లైన్", about: "IS-Advisor గురించి", aboutBody: "కొనుగోలు కోసం వర్తించే భారతీయ ప్రమాణాలను IS-Advisor సిఫార్సు చేస్తుంది.", describe: "కొనుగోలు అవసరాన్ని వివరించండి", uploadTender: "టెండర్‌ను అప్‌లోడ్ చేయండి", characters: "అక్షరాలు", clear: "తొలగించు", remove: "తొలగించు", extracting: "పత్రం నుండి వచనాన్ని తీస్తోంది…", error: "ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.", retry: "మళ్లీ ప్రయత్నించండి", newAnalysis: "కొత్త విశ్లేషణ" },
  ur: { dashboard: "ڈیش بورڈ", analyzeTender: "ٹینڈر کا تجزیہ", settings: "ترتیبات", heading: "آپ آج کیا خرید رہے ہیں؟", subheading: "مصنوعہ یا ضرورت بیان کریں، یا قابل اطلاق بھارتی معیارات تلاش کرنے کے لیے ٹینڈر اپ لوڈ کریں۔", placeholder: "مثال: بیرونی بلدیاتی سڑکوں کے لیے 90W LED اسٹریٹ لائٹس", analyze: "تجزیہ", example: "ایک مثال آزمائیں", led: "90W LED اسٹریٹ لائٹس", pump: "مرکزی پانی کے پمپ", upload: "ٹینڈر اپ لوڈ کریں", drop: "ٹینڈر یہاں رکھیں", pdf: "PDF یا TXT، 25MB تک", appearance: "ظاہری شکل", language: "زبان", preferences: "تجزیاتی ترجیحات", recommendations: "سفارشات", system: "نظام", light: "روشن", dark: "تاریک", status: "نظام کی حالت", online: "بیک اینڈ آن لائن", offline: "بیک اینڈ آف لائن", about: "IS-Advisor کے بارے میں", aboutBody: "IS-Advisor خریداری کے لیے قابل اطلاق بھارتی معیارات کی سفارش کرتا ہے۔", describe: "خریداری کی ضرورت بیان کریں", uploadTender: "ٹینڈر اپ لوڈ کریں", characters: "حروف", clear: "صاف کریں", remove: "ہٹائیں", extracting: "دستاویز سے متن نکالا جا رہا ہے…", error: "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔", retry: "دوبارہ کوشش", newAnalysis: "نیا تجزیہ" },
};

const generic: Record<string, LocaleWords> = {
  brx: { ...words.hi, dashboard: "नों गोसो होनाय?", analyzeTender: "टेनडार बिसोरनाय", settings: "सेटिं", heading: "आं दिनै मा खालामगोन?", subheading: "जोंनाय सामग्रि एबा जाथाय बिबुंनाय, एबा टेनडार अपलोड खालाम।", placeholder: "जेरै: 90W LED स्ट्रिट लाइट", analyze: "बिसोर", example: "गोसो नाय", upload: "टेनडार अपलोड", drop: "बेयाव टेनडार हो", pdf: "PDF एबा TXT, 25MB सिम", language: "राव", describe: "खरिदार जाथाय बिबुं", uploadTender: "टेनडार अपलोड", clear: "सुफुं", remove: "दोन", extracting: "दस्ताबेज निफ्राय लिरथुम लानाय…", error: "माबा गोरोन्थि जादों। फिन नाय।", retry: "फिन नाय", newAnalysis: "गोदान बिसोरनाय" },
  doi: { ...words.hi, dashboard: "डैशबोर्ड", analyzeTender: "टेंडर विश्लेषण", settings: "सेटिंगां", heading: "अज्ज तुसें केह खरीददे ओ?", subheading: "इक उत्पाद जां लोड़ दस्सो, जां लागू भारतीय मानकां लेई टेंडर अपलोड करो।", placeholder: "जिवें: 90W LED स्ट्रीट लाइट", analyze: "विश्लेषण", example: "इक मिसाल आजमाओ", upload: "टेंडर अपलोड करो", drop: "इत्थे टेंडर पाओ", pdf: "PDF जां TXT, 25MB तगर", language: "भाशा", describe: "खरीद दी लोड़ दस्सो", uploadTender: "टेंडर अपलोड करो", clear: "साफ करो", remove: "कड्ढो", extracting: "दस्तावेज थमां पाठ कड्ढेआ जा करदा ऐ…", error: "कुछ गलत होआ। दोबारा कोशिश करो।", retry: "दोबारा कोशिश", newAnalysis: "नमां विश्लेषण" },
  ks: { ...words.hi, dashboard: "ڈیش بورڈ", analyzeTender: "ٹینڈر تجزیہ", settings: "ترتیبات", heading: "تُہۍ وُن چھُو اَز خریدان؟", subheading: "اَکھ چیز یا ضرورت بیان کریو، یا ٹینڈر اپلوڈ کریو۔", placeholder: "مثال: 90W LED اسٹریٹ لائٹس", analyze: "تجزیہ", example: "مثال آزماؤ", upload: "ٹینڈر اپلوڈ", drop: "ٹینڈر ییِتھ پَیٹھ", pdf: "PDF یا TXT، 25MB تام", language: "زبان", describe: "خریداری ضرورت بیان کریو", uploadTender: "ٹینڈر اپلوڈ", clear: "صاف کریو", remove: "ہٹاؤ", extracting: "دستاویزہٕ پٮ۪ٹھ متن کڈان…", error: "کِہنہ غلط گژھ۔ دوبارہ کوشش کریو۔", retry: "دوبارہ کوشش", newAnalysis: "نَو تجزیہ" },
  kok: { ...words.hi, dashboard: "डॅशबोर्ड", analyzeTender: "टेंडर विश्लेशण", settings: "सेटींग्स", heading: "आयज तुमी कितें घेता?", subheading: "उत्पादन वा गरज सांगात, वा लागू भारतीय मानकां खातीर टेंडर अपलोड करात.", placeholder: "देखीक: 90W LED स्ट्रीट लायटी", analyze: "विश्लेशण", example: "एक उदाहरण पळयात", upload: "टेंडर अपलोड करात", drop: "हांगा टेंडर दियात", pdf: "PDF वा TXT, 25MB मेरेन", language: "भास", describe: "खरेदीची गरज सांगात", uploadTender: "टेंडर अपलोड करात", clear: "साफ करात", remove: "काडात", extracting: "दस्तावेजातल्यान मजकूर काडतात…", error: "कायतरी चुकलां. परत यत्न करात.", retry: "परत यत्न", newAnalysis: "नवो विश्लेशण" },
  mai: { ...words.hi, dashboard: "डैशबोर्ड", analyzeTender: "टेंडर विश्लेषण", settings: "सेटिंग", heading: "आइ अहाँ की खरीद रहल छ���?", subheading: "कोनो उत्पाद अथवा जरूरतक वर्णन करू, अथवा भारतीय मानक लेल टेंडर अपलोड करू।", placeholder: "जेना: 90W LED स्ट्रीट लाइट", analyze: "विश्लेषण", example: "उदाहरण देखू", upload: "टेंडर अपलोड करू", drop: "एतय टेंडर राखू", pdf: "PDF अथवा TXT, 25MB धरि", language: "भाषा", describe: "खरीदक जरूरतक ��र्णन करू", uploadTender: "टेंडर अपलोड करू", clear: "साफ करू", remove: "हटाउ", extracting: "दस्तावेज सँ पाठ निकालल जा रहल अछि…", error: "किछु गलत भेल। फेर प्रयास करू।", retry: "फेर प्रयास", newAnalysis: "नव विश्लेषण", history: "इतिहास", recentAnalyses: "हालक विश्लेषण", yourHistory: "अहाँक विश्लेषण इतिहास", clearHistory: "इतिहास साफ करू", noAnalyses: "अखन धरि कोनो विश्लेषण नहि", analyzeTenderAction: "टेंडर विश्लेषण करू", justNow: "अभी", minutesAgo: "{{count}} मिनट पहिने", hoursAgo: "{{count}} घंटा पहिने", daysAgo: "{{count}} दिन पहिने" },
  mni: { ...words.bn, dashboard: "ꯗꯦꯁꯕꯣꯔꯗ", analyzeTender: "ꯇꯦꯟꯗꯔ ꯑꯅꯥꯂꯥꯏꯖ", settings: "ꯁꯦꯇꯤꯡ", heading: "ꯅꯪꯅ ꯅꯨꯃꯤꯠꯇ ꯀꯔꯤ ꯂꯩꯁꯤꯅꯕꯒꯦ?", subheading: "ꯃꯐꯝ ꯑꯃꯁꯨꯡ ꯇꯦꯟꯗꯔ ꯑꯄꯂꯣꯗ ꯇꯧꯕꯤꯌꯨ।", placeholder: "ꯃꯁꯤꯅꯥ: 90W LED ꯁ꯭ꯇ꯭ꯔꯤꯠ ꯂꯥꯏꯠ", analyze: "ꯑꯅꯥꯂꯥꯏꯖ", example: "ꯑꯃ ꯃꯁꯥꯟ ꯅꯣꯡ", upload: "ꯇꯦꯟꯗꯔ ꯑꯄꯂꯣꯗ", drop: "ꯃꯐꯝ ꯑꯁꯤꯗ ꯇꯦꯟꯗꯔ ꯊꯝꯃꯨ", pdf: "PDF ꯅꯠꯇ꯭ꯔꯒꯥ TXT, 25MB", language: "ꯂꯣꯟ", describe: "ꯈꯔꯤꯗꯥꯔꯤ ꯄꯥꯝꯕ ꯁꯥꯟꯗꯣꯛꯄꯤꯌꯨ", uploadTender: "ꯇꯦꯟꯗꯔ ꯑꯄꯂꯣꯗ", clear: "ꯁꯥꯐ", remove: "ꯈꯣꯠꯄꯤꯌꯨ", extracting: "ꯗꯣꯀꯨꯃꯦꯟꯇ ꯅꯤꯡꯊꯤꯅ ꯂꯩ…", error: "ꯀꯔꯤꯒꯤ ꯌꯥꯎꯗꯦ। ꯑꯃꯨꯛ ꯑꯥꯏꯌꯨ।", retry: "ꯑꯃꯨꯛ ꯑꯥꯏ", newAnalysis: "ꯑꯅꯧꯕ ꯑꯅꯥꯂꯥꯏꯖ" },
  ne: { ...words.hi, dashboard: "ड्यासबोर्ड", analyzeTender: "टेन्डर विश्लेषण", settings: "सेटिङ", heading: "आज तपाईं के खरिद गर्दै हुनुहुन्छ?", subheading: "उत्पादन वा आवश्यकता वर्णन गर्न���होस्, वा भारतीय मापदण्डका लागि टेन्डर अपलोड गर्नुहोस्।", placeholder: "जस्तै: 90W LED सडक बत्ती", analyze: "विश्लेषण", example: "उदाहरण प्रयास गर्नुहोस्", upload: "टेन्डर अपलोड गर्नुहोस्", drop: "यहाँ टेन्डर राख्नुहोस्", pdf: "PDF वा TXT, 25MB सम्म", language: "भाषा", describe: "खरिद आवश्यकता वर्णन गर्नुहोस्", uploadTender: "टेन्डर अपलोड गर्नुहोस्", clear: "सफा", remove: "हटाउनुहोस्", extracting: "कागजातबाट पाठ निकालिँदैछ…", error: "केही गलत भयो। फेरि प्रयास गर्नुहोस्।", retry: "फेरि प्रयास", newAnalysis: "नयाँ विश्लेषण" },
  or: { ...words.hi, dashboard: "ଡ୍ୟାସବୋର୍ଡ", analyzeTender: "ଟେଣ୍ଡର ବିଶ୍ଳେଷଣ", settings: "ସେଟିଂ", heading: "ଆଜି ଆପଣ କଣ କିଣୁଛନ୍ତି?", subheading: "ଉତ୍ପାଦ କିମ୍ବା ଆବଶ୍ୟକତା ବର୍ଣ୍ଣନା କରନ୍ତୁ, କିମ୍ବା ଭାରତୀୟ ମାନକ ପାଇଁ ଟେଣ୍ଡର ଅପଲୋଡ କରନ୍ତୁ।", placeholder: "ଉଦାହରଣ: 90W LED ଷ୍ଟ୍ରିଟ ଲାଇଟ", analyze: "ବିଶ୍ଳେଷଣ", example: "ଉଦାହରଣ ଚେଷ୍ଟା କରନ୍ତୁ", upload: "ଟେଣ୍ଡର ଅପଲୋଡ କରନ୍ତୁ", drop: "ଏଠାରେ ଟେଣ୍ଡର ରଖନ୍ତୁ", pdf: "PDF କିମ୍ବା TXT, 25MB ପର୍ଯ୍ୟନ୍ତ", language: "ଭାଷା", describe: "କ୍ରୟ ଆବଶ୍ୟକତା ବର୍ଣ୍ଣନା କରନ୍ତୁ", uploadTender: "ଟେଣ୍ଡର ଅପଲୋଡ କରନ୍ତୁ", clear: "ସଫା କରନ୍ତୁ", remove: "ଅପସାରଣ", extracting: "ଦଲିଲରୁ ପାଠ ବାହାର କରାଯାଉଛି…", error: "କିଛି ଭୁଲ ହେଲା। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।", retry: "ପୁଣି ଚେଷ୍ଟା", newAnalysis: "ନୂତନ ବିଶ୍ଳେଷଣ" },
  sa: { ...words.hi, dashboard: "डैशबोर्ड", analyzeTender: "निविदा विश्लेषणम्", settings: "विन्यासाः", heading: "अद्य भवान् किं क्रयणं करोति?", subheading: "उत्पादं आवश्यकतां वा वर्णयतु, अथवा भारतीयमानकानां कृते निविदां स्थापयतु।", placeholder: "यथा: 90W LED मार्गदीपाः", analyze: "विश्लेषयतु", example: "उदाहरणं प्रयतताम्", upload: "निविदां स्थापयतु", drop: "अत्र निविदां स्थापयतु", pdf: "PDF अथवा TXT, 25MB पर्यन्तम्", language: "भाषा", describe: "क्रयणस्य आवश्यकतां वर्णयतु", uploadTender: "निविदां स्थापयतु", clear: "शोधयतु", remove: "अपनयतु", extracting: "दस्तावेजात् पाठः निष्कास्यते…", error: "किञ्चित् दोषः अभवत्। पुनः प्रयतताम्।", retry: "पुनः प्रयतताम्", newAnalysis: "नूतनं विश्लेषणम्" },
  sat: { ...words.hi, dashboard: "ᱰᱮᱥᱵᱚᱨᱰ", analyzeTender: "ᱴᱮᱱᱰᱟᱨ ᱵᱤᱥᱞᱮᱥᱚᱱ", settings: "ᱥᱮᱴᱤᱝ", heading: "ᱱᱤᱫᱟ ᱟᱢ ᱪᱮᱫ ᱠᱤᱱᱟᱹ?", subheading: "ᱡᱤᱱᱤᱥ ᱥᱮ ᱠᱟᱹᱹᱢᱤ ᱵᱟᱹᱨᱟᱭ, ᱟᱨ ᱴᱮᱱᱰᱟᱨ ᱟᱯᱞᱳᱰ ᱢᱮ।", placeholder: "ᱡᱮᱞᱮᱠᱟ: 90W LED ᱥᱴᱨᱤᱴ ᱞᱟᱭᱤᱴ", analyze: "ᱵᱤᱥᱞᱮᱥᱚᱱ", example: "ᱢᱤᱫ ᱡᱷᱚᱸᱠᱟ ᱧᱮᱞ", upload: "ᱴᱮᱱᱰᱟᱨ ᱟᱯᱞᱳᱰ", drop: "ᱱᱚᱰᱮ ᱴᱮᱱᱰᱟᱨ ᱫᱚᱦᱚ", pdf: "PDF ᱥᱮ TXT, 25MB", language: "ᱯᱟᱹᱨᱥᱤ", describe: "ᱠᱤᱱᱟᱹ ᱠᱟᱹᱢᱤ ᱵᱟᱹᱨᱟᱭ", uploadTender: "ᱴᱮᱱᱰᱟᱨ ᱟᱯᱞᱳᱰ", clear: "ᱥᱟᱯᱷᱟ", remove: "ᱚᱛᱟᱭ", extracting: "ᱫᱚᱞᱤᱞ ᱠᱷᱚᱱ ᱯᱟᱹᱴᱷ ᱚᱫᱚᱠ…", error: "ᱪᱮᱫ ᱦᱟᱹᱲᱤᱡ ᱮᱱᱟ। ᱛᱟᱭᱚᱢ ᱯᱷᱮᱨᱟᱹ ᱧᱮᱞᱢᱮ।", retry: "ᱛᱟᱭᱚᱢ ᱧᱮᱞ", newAnalysis: "ᱱᱟᱣᱟ ᱵᱤᱥᱞᱮᱥᱚᱱ" },
  sd: { ...words.ur, dashboard: "ڊيش بورڊ", analyzeTender: "ٽينڊر تجزيو", settings: "سيٽنگون", heading: "اڄ توهان ڇا خريد ڪري رهيا آهيو؟", subheading: "پيداوار يا ضرورت بيان ڪريو، يا هندستاني معيارن لاءِ ٽينڊر اپلوڊ ڪريو.", placeholder: "مثال: 90W LED اسٽريٽ لائيٽ", analyze: "تجزيو", example: "مثال آزمايو", upload: "ٽينڊر اپلوڊ ڪريو", drop: "هتي ٽينڊر رکو", pdf: "PDF يا TXT، 25MB تائين", language: "ٻولي", describe: "خريداري جي ضرورت بيان ڪريو", uploadTender: "ٽينڊر اپلوڊ ڪريو", clear: "صاف ڪريو", remove: "هٽايو", extracting: "دستاويز مان متن ڪڍيو پيو وڃي…", error: "ڪجهه غلط ٿيو. ٻيهر ڪوشش ڪريو.", retry: "ٻيهر ڪوشش", newAnalysis: "نئون تجزيو" },
};

const all = { ...words, ...generic };
export const INDIC_TRANSLATIONS: Partial<Record<Exclude<LanguageCode, "en" | "hi">, Record<string, unknown>>> = Object.fromEntries(
  Object.entries(all).map(([code, value]) => [code, base(value)]),
) as Partial<Record<Exclude<LanguageCode, "en" | "hi">, Record<string, unknown>>>;

export const translationFor = (code: LanguageCode) => INDIC_TRANSLATIONS[code as keyof typeof INDIC_TRANSLATIONS] ?? {};

// Keep the app's domain name and BIS identifiers unchanged across locales.
export { base, words, generic, all };
