import type { LanguageCode } from "./index";

// Shared translated UI vocabulary for the Indian language locales. The English
// resource remains the fallback for keys that are intentionally domain-specific
// (including BIS standard identifiers and evidence returned by the backend).
export const INDIC_TRANSLATIONS: Partial<Record<Exclude<LanguageCode, "en" | "hi">, Record<string, unknown>>> = {
  as: { nav: { dashboard: "ডেশ্বব’ৰ্ড", analyze: "নিবিদা বিশ্লেষণ", settings: "ছেটিংছ" }, settings: { title: "ছেটিংছ", appearance: "উপস্থিতি", language: "ভাষা", preferences: "বিশ্লেষণৰ পছন্দ", topK: "পৰামৰ্শৰ সংখ্যা", systemStatus: "চিস্টেমৰ অৱস্থা", about: "IS-Advisor ৰ বিষয়ে" }, dashboard: { analyze: "বিশ্লেষণ", tryExample: "এটা উদাহৰণ চেষ্টা কৰক" }, analyze: { clear: "পৰিষ্কাৰ", analyzeButton: "বিশ্লেষণ" }, results: { newAnalysis: "নতুন বিশ্লেষণ" } },
  bn: { nav: { dashboard: "ড্যাশবোর্ড", analyze: "টেন্ডার বিশ্লেষণ", settings: "সেটিংস" }, settings: { title: "সেটিংস", appearance: "চেহারা", language: "ভাষা", preferences: "বিশ্লেষণের পছন্দ", topK: "সুপারিশের সংখ্যা", systemStatus: "সিস্টেমের অবস্থা", about: "IS-Advisor সম্পর্কে" }, dashboard: { analyze: "বিশ্লেষণ", tryExample: "একটি উদাহরণ চেষ্টা করুন" }, analyze: { clear: "পরিষ্কার", analyzeButton: "বিশ্লেষণ" }, results: { newAnalysis: "নতুন বিশ্লেষণ" } },
  gu: { nav: { dashboard: "ડેશબોર્ડ", analyze: "ટેન્ડરનું વિશ્લેષણ", settings: "સેટિંગ્સ" }, settings: { title: "સેટિંગ્સ", appearance: "દેખાવ", language: "ભાષા", preferences: "વિશ્લેષણ પસંદગીઓ", topK: "ભલામણોની સંખ્યા", systemStatus: "સિસ્ટમ સ્થિતિ", about: "IS-Advisor વિશે" }, dashboard: { analyze: "વિશ્લેષણ", tryExample: "ઉદાહરણ અજમાવો" }, analyze: { clear: "સાફ કરો", analyzeButton: "વિશ્લેષણ" }, results: { newAnalysis: "નવું વિશ્લેષણ" } },
  kn: { nav: { dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", analyze: "ಟೆಂಡರ್ ವಿಶ್ಲೇಷಣೆ", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು" }, settings: { title: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", appearance: "ಗೋಚರತೆ", language: "ಭಾಷೆ", preferences: "ವಿಶ್ಲೇಷಣೆ ಆದ್ಯತೆಗಳು", topK: "ಶಿಫಾರಸುಗಳ ಸಂಖ್ಯೆ", systemStatus: "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ", about: "IS-Advisor ಕುರಿತು" }, dashboard: { analyze: "ವಿಶ್ಲೇಷಿಸಿ", tryExample: "ಉದಾಹರಣೆ ಪ್ರಯತ್ನಿಸಿ" }, analyze: { clear: "ತೆರವುಗೊಳಿಸಿ", analyzeButton: "ವಿಶ್ಲೇಷಿಸಿ" }, results: { newAnalysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ" } },
  ml: { nav: { dashboard: "ഡാഷ്ബോർഡ്", analyze: "ടെൻഡർ വിശകലനം", settings: "ക്രമീകരണങ്ങൾ" }, settings: { title: "ക്രമീകരണങ്ങൾ", appearance: "രൂപം", language: "ഭാഷ", preferences: "വിശകലന മുൻഗണനകൾ", topK: "ശുപാർശകളുടെ എണ്ണം", systemStatus: "സിസ്റ്റം നില", about: "IS-Advisor-നെ കുറിച്ച്" }, dashboard: { analyze: "വിശകലനം", tryExample: "ഒരു ഉദാഹരണം ശ്രമിക്കുക" }, analyze: { clear: "മായ്ക്കുക", analyzeButton: "വിശകലനം" }, results: { newAnalysis: "പുതിയ വിശകലനം" } },
  mr: { nav: { dashboard: "डॅशबोर्ड", analyze: "निविदेचे विश्लेषण", settings: "सेटिंग्ज" }, settings: { title: "सेटिंग्ज", appearance: "स्वरूप", language: "भाषा", preferences: "विश्लेषण प्राधान्ये", topK: "शिफारसींची संख्या", systemStatus: "प्रणाली स्थिती", about: "IS-Advisor विषयी" }, dashboard: { analyze: "विश्लेषण", tryExample: "उदाहरण वापरून पहा" }, analyze: { clear: "पुसा", analyzeButton: "विश्लेषण" }, results: { newAnalysis: "नवीन विश्लेषण" } },
  pa: { nav: { dashboard: "ਡੈਸ਼ਬੋਰਡ", analyze: "ਟੈਂਡਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ", settings: "ਸੈਟਿੰਗਾਂ" }, settings: { title: "ਸੈਟਿੰਗਾਂ", appearance: "ਦਿੱਖ", language: "ਭਾਸ਼ਾ", preferences: "ਵਿਸ਼ਲੇਸ਼ਣ ਤਰਜੀਹਾਂ", topK: "ਸਿਫ਼ਾਰਸ਼ਾਂ ਦੀ ਗਿਣਤੀ", systemStatus: "ਸਿਸਟਮ ਸਥਿਤੀ", about: "IS-Advisor ਬਾਰੇ" }, dashboard: { analyze: "ਵਿਸ਼ਲੇਸ਼ਣ", tryExample: "ਇੱਕ ਉਦਾਹਰਨ ਅਜ਼ਮਾਓ" }, analyze: { clear: "ਸਾਫ਼ ਕਰੋ", analyzeButton: "ਵਿਸ਼ਲੇਸ਼ਣ" }, results: { newAnalysis: "ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ" } },
  ta: { nav: { dashboard: "டாஷ்போர்டு", analyze: "டெண்டர் பகுப்பாய்வு", settings: "அமைப்புகள்" }, settings: { title: "அமைப்புகள்", appearance: "தோற்றம்", language: "மொழி", preferences: "பகுப்பாய்வு விருப்பங்கள்", topK: "பரிந்துரைகளின் எண்ணிக்கை", systemStatus: "கணினி நிலை", about: "IS-Advisor பற்றி" }, dashboard: { analyze: "பகுப்பாய்வு", tryExample: "ஓர் உதாரணத்தை முயற்சிக்கவும்" }, analyze: { clear: "அழி", analyzeButton: "பகுப்பாய்வு" }, results: { newAnalysis: "புதிய பகுப்பாய்வு" } },
  te: { nav: { dashboard: "డ్యాష్‌బోర్డ్", analyze: "టెండర్ విశ్లేషణ", settings: "సెట్టింగ్‌లు" }, settings: { title: "సెట్టింగ్‌లు", appearance: "రూపురేఖలు", language: "భాష", preferences: "విశ్లేషణ ప్రాధాన్యతలు", topK: "సిఫార్సుల సంఖ్య", systemStatus: "సిస్టమ్ స్థితి", about: "IS-Advisor గురించి" }, dashboard: { analyze: "విశ్లేషించు", tryExample: "ఉదాహరణ ప్రయత్నించండి" }, analyze: { clear: "తొలగించు", analyzeButton: "విశ్లేషించు" }, results: { newAnalysis: "కొత్త విశ్లేషణ" } },
  ur: { nav: { dashboard: "ڈیش بورڈ", analyze: "ٹینڈر کا تجزیہ", settings: "ترتیبات" }, settings: { title: "ترتیبات", appearance: "ظاہری شکل", language: "زبان", preferences: "تجزیاتی ترجیحات", topK: "سفارشات کی تعداد", systemStatus: "نظام کی حالت", about: "IS-Advisor کے بارے میں" }, dashboard: { analyze: "تجزیہ", tryExample: "ایک مثال آزمائیں" }, analyze: { clear: "صاف کریں", analyzeButton: "تجزیہ" }, results: { newAnalysis: "نیا تجزیہ" } },
};

export const translationFor = (code: LanguageCode) => INDIC_TRANSLATIONS[code as keyof typeof INDIC_TRANSLATIONS] ?? {};
